namespace AlbumCoverScreenSaver.Shared.Tests;

/// <summary>
/// The sky of Starfield Orbit.
/// </summary>
/// <remarks>
/// The star field is generated by a hash rather than stored, which makes it free
/// but also makes it silently fragile: it would still produce a perfectly
/// convincing sky if it were wrong, just a different one from the Mac's, and
/// nobody would ever notice. So the hash is checked against its own arithmetic,
/// and the properties that make it usable as a sky are checked directly.
/// </remarks>
public static class StarfieldTests
{
    public static void Register(TestRunner runner)
    {
        Stars(runner);
        Orbits(runner);
    }

    private static void Stars(TestRunner runner)
    {
        runner.Group("Starfield: the stars");

        runner.Add("every star lands on screen", () =>
        {
            for (var i = 0; i < Starfield.Count; i++)
            {
                var star = Starfield.At(i);

                Check.True(star.X01 is >= 0 and < 1, $"star {i} x is {star.X01}");
                Check.True(star.Y01 is >= 0 and < 1, $"star {i} y is {star.Y01}");
                Check.True(star.Depth is >= 0 and < 1, $"star {i} depth is {star.Depth}");
            }
        });

        runner.Add("the same star is in the same place every time", () =>
        {
            // The whole reason for a hash rather than stored positions. If this
            // ever stops being true the sky crawls, which is the one thing a
            // star field must not do.
            for (var i = 0; i < Starfield.Count; i++)
            {
                Check.Equal(Starfield.At(i), Starfield.At(i), $"star {i}");
            }
        });

        runner.Add("the hash is computed in double precision", () =>
        {
            // Not a style choice. The hash keeps only the fractional tail of a
            // very large number, so it is maximally sensitive to precision: in
            // single precision it gives a perfectly good sky, just a different
            // one from the Mac's, and nobody would ever catch it by looking.
            //
            // This compares against the single-precision answer and requires
            // them to differ, which they do for most indices.
            var differences = 0;

            for (var i = 1; i < Starfield.Count; i++)
            {
                var asDouble = Starfield.At(i).X01;

                var single = MathF.Sin(i * 12.9898f) * 43758.5453f;
                var asFloat = single - MathF.Floor(single);

                if (Math.Abs(asDouble - asFloat) > 0.01) differences++;
            }

            Check.True(differences > Starfield.Count / 2,
                $"only {differences} of {Starfield.Count} stars differ, which suggests single precision");
        });

        runner.Add("the stars are spread rather than clumped", () =>
        {
            // A hash that happened to correlate would put every star in a band,
            // which is the failure mode these idioms actually have.
            var columns = new int[10];
            var rows = new int[10];

            for (var i = 0; i < Starfield.Count; i++)
            {
                var star = Starfield.At(i);
                columns[(int)(star.X01 * 10)]++;
                rows[(int)(star.Y01 * 10)]++;
            }

            foreach (var count in columns) Check.True(count > 4, $"a tenth of the sky holds only {count} stars");
            foreach (var count in rows) Check.True(count > 4, $"a tenth of the sky holds only {count} stars");
        });

        runner.Add("near stars are bigger, brighter and faster", () =>
        {
            Check.True(Starfield.SizeOf(1) > Starfield.SizeOf(0) * 4, "size");
            Check.True(Starfield.AlphaOf(1) > Starfield.AlphaOf(0) * 4, "brightness");

            // Six times, which is what gives the field any depth at all.
            Check.Close(2.0, Starfield.DriftOf(1, 0), 0.0001, "the far ones barely move");
            Check.Close(12.0, Starfield.DriftOf(1, 1), 0.0001, "the near ones cross in seconds");
        });

        runner.Add("no star is ever invisible or a single pixel", () =>
        {
            for (var i = 0; i < Starfield.Count; i++)
            {
                var depth = Starfield.At(i).Depth;

                Check.True(Starfield.SizeOf(depth) >= 0.5f, "big enough to draw");
                Check.True(Starfield.AlphaOf(depth) >= 0.15f, "bright enough to see");
                Check.True(Starfield.AlphaOf(depth) <= 0.70f, "and never brighter than the covers");
            }
        });
    }

    private static void Orbits(TestRunner runner)
    {
        runner.Group("Starfield: the orbiting covers");

        runner.Add("inner orbits go round faster, as they do in the sky", () =>
        {
            var inner = Starfield.SpeedAt(0.20, slower: false);
            var outer = Starfield.SpeedAt(0.52, slower: false);

            Check.Close(0.789, inner, 0.001, "the innermost");
            Check.Close(0.429, outer, 0.001, "the outermost");
            Check.True(inner > outer, "and the inner one wins");
        });

        runner.Add("the coin flip stops covers locking together", () =>
        {
            // Two covers that happened to share a radius would otherwise stay
            // side by side forever, which looks like a bug in the orbit rather
            // than a coincidence.
            var fast = Starfield.SpeedAt(0.3, slower: false);
            var slow = Starfield.SpeedAt(0.3, slower: true);

            Check.Close(fast * 0.85, slow, 0.0001, "the slower one is 85% of the pace");
        });

        runner.Add("the orbit is a plane seen nearly edge-on, not a hoop", () =>
        {
            // A third of the vertical travel of the horizontal. Without the
            // squash the covers go round in a circle and the sun stops looking
            // like it is in the middle of anything.
            var side = Starfield.PlaceOrbiter(0, 1000f, 0.4f, 0.1f);
            var top = Starfield.PlaceOrbiter(Math.PI / 2, 1000f, 0.4f, 0.1f);

            Check.Close(400.0, side.OffsetX, 0.01, "the full width");
            Check.Close(136.0, top.OffsetUp, 0.01, "but only a third of the height");
        });

        runner.Add("a cover in front is larger and a cover behind is smaller", () =>
        {
            var behind = Starfield.PlaceOrbiter(Math.PI / 2, 1000f, 0.4f, 0.1f);
            var infront = Starfield.PlaceOrbiter(-Math.PI / 2, 1000f, 0.4f, 0.1f);

            Check.Close(1.0, behind.Depth, 0.0001, "far side");
            Check.Close(0.0, infront.Depth, 0.0001, "near side");
            Check.Close(75.0, behind.Size, 0.01, "three quarters of nominal");
            Check.Close(125.0, infront.Size, 0.01, "and a quarter over");
        });

        runner.Add("the two halves of the orbit are split at the right moment", () =>
        {
            // The only depth sorting there is: everything on the far side is
            // drawn before the sun and everything on the near side after it.
            Check.True(Starfield.IsBehind(Math.PI / 2), "the far side");
            Check.False(Starfield.IsBehind(-Math.PI / 2), "the near side");
            Check.True(Starfield.IsBehind(0), "and the crossing point belongs behind");
        });

        runner.Add("depth changes smoothly all the way round", () =>
        {
            // It drives both size and shading, so a discontinuity would be a
            // cover that visibly jumps as it passes the sun.
            var previous = Starfield.PlaceOrbiter(-Math.PI, 1000f, 0.4f, 0.1f).Depth;

            for (var step = 1; step <= 360; step++)
            {
                var angle = -Math.PI + (step * Math.PI * 2 / 360);
                var depth = Starfield.PlaceOrbiter(angle, 1000f, 0.4f, 0.1f).Depth;

                Check.True(Math.Abs(depth - previous) < 0.02f, $"depth jumped at {step} degrees");
                previous = depth;
            }
        });

        runner.Add("the count is clamped, and a preview gets five", () =>
        {
            Check.Equal(14, Starfield.OrbiterCount(14, false), "the default");
            Check.Equal(3, Starfield.OrbiterCount(0, false), "never none");
            Check.Equal(40, Starfield.OrbiterCount(400, false), "never absurd");
            Check.Equal(5, Starfield.OrbiterCount(40, true), "a preview is a thumbnail");
        });
    }
}
