<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>AlbumCoverScreenSaver.Shared</RootNamespace>
    <AssemblyName>AlbumCoverScreenSaver.Shared</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AlbumCoverScreenSaver.Shared.Tests" />
  </ItemGroup>

</Project>
